DROP TABLE unit_types CASCADE;
DROP TABLE manufacturers CASCADE;
DROP TABLE pallets CASCADE;
DROP TABLE tickets CASCADE;
DROP TABLE unit_types CASCADE;
DROP TABLE ticket_types CASCADE;
DROP TABLE customers CASCADE;
DROP TABLE units CASCADE;
DROP TABLE locations CASCADE;

/*
DROP TABLE users CASCADE;
*/